// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repo

import (
	"database/sql"

	"github.com/google/uuid"
)

type Credential struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	Password string
}

type User struct {
	ID          uuid.UUID
	Username    string
	ParentCode  string
	DateOfBirth sql.NullTime
	Created     sql.NullTime
}
