version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  user-microservice:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://user:password@postgres/user_db?sslmode=disable"

  spelling-microservice:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - postgres
