CREATE DATABASE IF NOT EXISTS `users`;
CREATE DATABASE IF NOT EXISTS `spelling`;

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TYPE userRole AS ENUM('TEACHER','STUDENT')

CREATE TABLE students (
    id UUID PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    role userRole NOT NULL CHECK (role = 'STUDENT'),
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    parent_name VARCHAR(100),
    parent_email VARCHAR(100),
    parent_code VARCHAR(4),
    birthday DATE,
    academic_year VARCHAR(10),
    class_id UUID,
    FOREIGN KEY (class_id) REFERENCES classes(id)
);

CREATE TABLE teachers (
    id UUID PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role = 'TEACHER'),
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    school_name VARCHAR(100),
    classes UUID[],
    FOREIGN KEY (classes) REFERENCES classes(id)
);
