// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Credential struct {
	ID       int32
	UserID   pgtype.Int4
	Password pgtype.Text
}

type User struct {
	ID          int32
	Username    string
	ParentCode  pgtype.Text
	DateOfBirth pgtype.Date
	Created     pgtype.Timestamp
}
