// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package repo

import (
	"context"
	"database/sql"
)

const createCredentials = `-- name: CreateCredentials :exec
INSERT INTO credentials (id, user_id, password) VALUES($1,$2,crypt($3,'crypt-des'))
`

type CreateCredentialsParams struct {
	ID     string
	UserID string
	Crypt  string
}

func (q *Queries) CreateCredentials(ctx context.Context, arg CreateCredentialsParams) error {
	_, err := q.db.ExecContext(ctx, createCredentials, arg.ID, arg.UserID, arg.Crypt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, date_of_birth, parent_code) VALUES ($1, $2, $3, $4) RETURNING id, username, parent_code, date_of_birth, created
`

type CreateUserParams struct {
	ID          string
	Username    string
	DateOfBirth sql.NullTime
	ParentCode  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.DateOfBirth,
		arg.ParentCode,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.ParentCode,
		&i.DateOfBirth,
		&i.Created,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id == $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const findByUsername = `-- name: FindByUsername :one
SELECT id, username, parent_code, date_of_birth, created FROM users WHERE username = $1
`

func (q *Queries) FindByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, findByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.ParentCode,
		&i.DateOfBirth,
		&i.Created,
	)
	return i, err
}

const findCredentials = `-- name: FindCredentials :one
SELECT id FROM credentials WHERE user_id = $1 and password = crypt($2, 'crypt-des')
`

type FindCredentialsParams struct {
	UserID string
	Crypt  string
}

func (q *Queries) FindCredentials(ctx context.Context, arg FindCredentialsParams) (string, error) {
	row := q.db.QueryRowContext(ctx, findCredentials, arg.UserID, arg.Crypt)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, parent_code, date_of_birth, created FROM users where id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.ParentCode,
		&i.DateOfBirth,
		&i.Created,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, parent_code, date_of_birth, created FROM users
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.ParentCode,
			&i.DateOfBirth,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateParentCode = `-- name: UpdateParentCode :one
UPDATE users
SET parent_code = $2
WHERE id = $1
RETURNING id, username, parent_code, date_of_birth, created
`

type UpdateParentCodeParams struct {
	ID         string
	ParentCode string
}

func (q *Queries) UpdateParentCode(ctx context.Context, arg UpdateParentCodeParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateParentCode, arg.ID, arg.ParentCode)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.ParentCode,
		&i.DateOfBirth,
		&i.Created,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET date_of_birth = $2, username = $3
WHERE id = $1
RETURNING id, username, parent_code, date_of_birth, created
`

type UpdateUserParams struct {
	ID          string
	DateOfBirth sql.NullTime
	Username    string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.ID, arg.DateOfBirth, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.ParentCode,
		&i.DateOfBirth,
		&i.Created,
	)
	return i, err
}

