// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package repo

import (
	"context"
	"database/sql"
)

const createCredentials = `-- name: CreateCredentials :exec
INSERT INTO credentials ( user_id, password) VALUES($1,crypt($2,'crypt-des'))
`

type CreateCredentialsParams struct {
	UserID string
	Crypt  string
}

func (q *Queries) CreateCredentials(ctx context.Context, arg CreateCredentialsParams) error {
	_, err := q.db.ExecContext(ctx, createCredentials, arg.UserID, arg.Crypt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, date_of_birth, parent_code) VALUES ($1, $2, $3, $4) RETURNING id, username, parent_code, date_of_birth, created
`

type CreateUserParams struct {
	ID          string
	Username    string
	DateOfBirth sql.NullTime
	ParentCode  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.DateOfBirth,
		arg.ParentCode,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.ParentCode,
		&i.DateOfBirth,
		&i.Created,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, parent_code, date_of_birth, created FROM users where id == $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.ParentCode,
		&i.DateOfBirth,
		&i.Created,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, parent_code, date_of_birth, created FROM users
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.ParentCode,
			&i.DateOfBirth,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
