### create_user
POST {{protocol}}user.api.ext.localhost.spelling-app/create_user
Content-Type: application/json

{
  "username": "test_user_2",
  "password": "password123",
  "parent_code": "1234",
  "date_of_birth": "13-07-2002"
}

### list_users
POST {{protocol}}user.api.ext.localhost.spelling-app/list_users
Content-Type: application/json

{
}

### create_user -> todo fix date_of_birth parsing
POST http://localhost:8080/create_user
Content-Type: application/json

{
  "username": "test_user2",
  "password": "password123",
  "parent_code": "1234",
  "date_of_birth": "2002-01-02T00:00:00Z"
}

### login TODO: fix error logging
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "test_user",
  "password": "password123"
}

### update_parent_code
POST http://localhost:8080/edit_parent_details
Content-Type: application/json

{
  "user_id": "VVllNSUIGg03MrmrDWW52fJszDi9ITS2Ly6uWp5Okdc_user",
  "parent_code" : "2345"
}

### update_user
POST http://localhost:8080/edit_user
Content-Type: application/json

{
  "user_id": "VVllNSUIGg03MrmrDWW52fJszDi9ITS2Ly6uWp5Okdc_user",
  "date_of_birth" : "2002-01-02"
}

### update_user
POST http://localhost:8080/list_users
Content-Type: application/json

{
}

